version: "3"
services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    restart: unless-stopped

  cache:
    image: redis:6
    restart: unless-stopped

  directus:
    image: directus/directus:10.11.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
    restart: unless-stopped

  api:
    build:
      context: ./api
    ports:
      - 3000:3000
    depends_on:
      - database
      - cache
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: directus
      DATABASE_PASSWORD: directus
      DATABASE_NAME: directus
      REDIS_HOST: cache
      REDIS_PORT: 6379
    restart: unless-stopped
